version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.secure.address=:443
      - --entrypoints.whoami.address=:81
      - --certificatesResolvers.certs.acme.email=<email>
#      - --certificatesResolvers.certs.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.certs.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.certs.acme.storage=acme.json
      - --certificatesResolvers.certs.acme.keyType=RSA4096
#      - --certificatesResolvers.certs.acme.tlsChallenge=true
      - --certificatesResolvers.certs.acme.httpChallenge=true
      - --certificatesResolvers.certs.acme.httpChallenge.entryPoint=web
      - --providers.docker
      - --providers.docker.swarmMode=true
      - --providers.docker.swarmModeRefreshSeconds=60s
      - --providers.docker.network=web
      - --api.insecure
      - --metrics.influxdb=true
      - --metrics.influxdb.address=influxdb:8086
      - --metrics.influxdb.protocol=http
      - --metrics.influxdb.database=traefik
      - --log.level=DEBUG
      - --accesslog=true
      - --global.sendAnonymousUsage
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
      - "8090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/media/ssd/docker/traefik/acme.json:/acme.json"
    networks:
      - web
      - monitoring

  my-app:
    image: containous/whoami:latest
    deploy:
      labels:
#        - "traefik.http.routers.my-app.rule=PathPrefix(`/whoami`)"
        - "traefik.http.routers.my-app.rule=Host(`192.168.0.36`)"
        - "traefik.http.routers.my-app.entryPoints=whoami"
        - "traefik.http.services.my-app.loadbalancer.server.port=80"
#        - "traefik.http.middlewares.my-app-stripprefix.stripprefix.prefixes=/whoami"
        - "traefik.http.middlewares.auth_w.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/" # user/password
        - "traefik.http.routers.my-app.middlewares=auth_w"
    networks:
      - web


networks:
  web:
    external:
      name: web
  monitoring:
    external:
      name: monitoring


# Dashboard (https://localhost:8080)
# Route (http://whoami.docker.localhost/)
# Basic auth (login: user | password: password)